### ISSUE TITLE
关于代码提交

### ISSUE THREAD

**Issue by hulizhishang** [CSGrandeur/CSG-CPC-Discussion#3]
比如小鼠游戏那道题，我确实是点击了submit，在旁边的programming status也有记录，题目的status为answered and saved。但是点finish提交试卷后，再刷新发现题目的status变成了changed but not saved，不知道会不会影响最后的答题情况

**Comment by CSGrandeur** [comment]
应该已经解决了，可以用同学的账号在测试服试一下看
